[www]
user = appbox
group = appbox

listen = /run/php/php-fpm.sock
listen.owner = appbox
listen.group = appbox
listen.mode = 0660

pm = dynamic
pm.max_children = 25
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

php_admin_value[error_log] = /home/appbox/logs/php-fpm-www-error.log
php_admin_flag[log_errors] = on
